[global]
   workgroup = WORKGROUP
   server string = NAS-PRO
   netbios name = NAS-PRO
   security = user
   map to guest = Bad User
   guest account = nobody
   socket options = TCP_NODELAY SO_RCVBUF=65536 SO_SNDBUF=65536
   read raw = yes
   write raw = yes
   max xmit = 65536
   dead time = 15
   getwd cache = yes
   unix extensions = no
   browseable = yes
   local master = yes
   os level = 65
   preferred master = yes
   domain master = yes
   dns proxy = no
   wins support = yes
   server role = standalone server

[Public]
   path = /srv/nas/public
   browseable = yes
   read only = no
   guest ok = yes
   create mask = 0777
   directory mask = 0777
   force user = naspro
   force group = naspro

[Private]
   path = /srv/nas/private
   browseable = no
   read only = no
   guest ok = no
   create mask = 0700
   directory mask = 0700
   valid users = naspro
